version: '3.9'

services:
  app:
    build: .
    env_file:
      - .env
    volumes:
      - ./certs:/app/certs
    ports:
      - "443:443"
    volumes:
      - ./data:/app/data
      - ./static:/app/static
      - ./certs:/app/certs
